### PR TITLE
Fixed reading of IStream to handle IntPtr.Zero

### PR DESCRIPTION
**Pull request by andreas-eriksson**
This seems to resolve the issue.

I peeked at https://github.com/borgdylan/dotnet-cli/blob/master/src/Microsoft.Extensions.Testing.Abstractions/ComStreamWrapper.cs

I have not updated the version for the assembly or for the nuget package.

### CODE REVIEW

**Comment by Sicos1977** [comment]
Thanks for fixing

**Comment by Sicos1977** [comment]
I also published version 1.5.4 to NuGet

**Comment by andreas-eriksson** [comment]
Thanks for publishing 👍

**Comment by Sicos1977** [comment]
your welcome

**Pull request merged**
