### PR TITLE
IFilterTextReader Project converted to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by mgeramb**
I have converted the Project to .NET Standard 2.0 so it can be used for .NET Core and classic .NET Projects

### CODE REVIEW

**Comment by Sicos1977** [comment]
I don't think that this project will work on any other machine than the one that is running Windows. Under the hood IFilters are used and this is something that only exists in Windows.... not to be blunt but what is the point of converting this to .NET core to support other operating systems?

**Comment by mgeramb** [comment]
You are right, it will only work on windows but it can use the .NET Core runtime and the classic runtime

**Comment by mgeramb** [comment]
But the Integration build process must be changed also...

**Comment by Sicos1977** [comment]
If you put it like that then you have a good point. But I still think it is better to just upgrade to .NET 4.6.1 since that is the same version that .NET standard 2.0 uses. This way the project can be added in a .NET Standard 2.0 project but it will always give a warning that is possible will not work on other operating systems.

**Comment by Sicos1977** [comment]
This article explains when or when not to use .NET Standard (core) --> https://stackify.com/net-core-vs-net-framework/

**Pull request closed without merging**
